<a href="https://colab.research.google.com/github/danieleduardofajardof/DataSciencePrepMaterial/blob/main/1_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1. Linear Algebra


# Index:
- [1. Vectors and Matrices Operations](#vec-mat-op)
- [2. Eigenvalues and Eigenvectors](#eigen-values-vect)
- [3. Matrix Decomposition](#mat-decomp)

# 1. Vectors and Matrices Operations  <a name="vec-mat-op"></a>

Vectors and matrices are fundamental objects in linear algebra used to represent and manipulate data. This section explains key operations with both.

---

## Vectors

A **vector** is an ordered list of numbers that can represent points, directions, or quantities. For example, a 2-dimensional vector can be written as:

$$
\mathbf{v} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}
$$

### Vector Operations

### 1. **Addition and Subtraction**  
   To add or subtract two vectors, add or subtract their corresponding components.
- **Example:**

$$ \quad \mathbf{v} = \begin{bmatrix} 2 \\ 4 \end{bmatrix},
 \quad \mathbf{u} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}$$

     
Addition:

$$
\mathbf{u} + \mathbf{v} = \begin{bmatrix} 2+3 \\ 4+1 \end{bmatrix} = \begin{bmatrix} 5 \\ 5 \end{bmatrix}
$$

Subtraction:

$$
\mathbf{u} - \mathbf{v} = \begin{bmatrix} 2-3 \\ 4-1 \end{bmatrix} = \begin{bmatrix} -1 \\ 3 \end{bmatrix}
$$

### 2. **Scalar Multiplication**  
   Multiply each component of a vector by a scalar.

- **Example:**
     
$$
2 \cdot \mathbf{v} = 2 \cdot \begin{bmatrix} 3 \\ 1 \end{bmatrix} = \begin{bmatrix} 6 \\ 2 \end{bmatrix}
$$

### 3. **Dot Product (Inner Product)**  
   The dot product of two vectors is the sum of the products of their corresponding components.

- **Example:**

$$
\mathbf{u} \cdot \mathbf{v} = 2 \cdot 3 + 4 \cdot 1 = 6 + 4 = 10
$$

### 4. **Norm (Magnitude)**  
   The norm of a vector is its length.

- **Example:**

$$
\|\mathbf{v}\| = \sqrt{3^2 + 1^2} = \sqrt{9 + 1} = \sqrt{10}
$$

---

## Matrices

A **matrix** is a rectangular array of numbers. For example, a 2×2 matrix is written as:

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

### Matrix Operations

### 1. **Addition and Subtraction**  
   Add or subtract matrices by performing the operation on corresponding elements.

- **Example:**

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

$$
A + B = \begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}
$$

### 2. **Scalar Multiplication**  
   Multiply every element of a matrix by a scalar.

- **Example:**

$$
2A = \begin{bmatrix} 2\cdot1 & 2\cdot2 \\ 2\cdot3 & 2\cdot4 \end{bmatrix} = \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}
$$

### 3. **Matrix Multiplication**  
   Multiply two matrices by taking the dot product of rows of the first matrix with columns of the second.

- **Example:**

For

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix},
$$

the product \(AB\) is:

$$
AB = \begin{bmatrix}
1\cdot5 + 2\cdot7 & 1\cdot6 + 2\cdot8 \\
3\cdot5 + 4\cdot7 & 3\cdot6 + 4\cdot8
\end{bmatrix}
= \begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$$

### 4. **Transpose**  
   The transpose of a matrix \(A\), denoted \(A^T\), is obtained by swapping its rows with its columns.

- **Example:**

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \quad \Longrightarrow \quad A^T = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}
$$

### 5. **Determinant and Inverse (for Square Matrices)**  
- **Determinant:** A scalar value that can be computed from the elements of a square matrix.
- **Inverse:** The matrix \(A^{-1}\) is defined such that \(A A^{-1} = I\), where \(I\) is the identity matrix.  

For a 2×2 matrix

$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix},
$$

the inverse (if it exists) is given by

$$
A^{-1} = \frac{1}{ad-bc}\begin{bmatrix} d & -b \\ -c & a \end{bmatrix},
$$

provided that \(ad-bc \neq 0\).

---

## Summary

- **Vectors:**  
  - Represent quantities with direction and magnitude.
  - Operations include addition, subtraction, scalar multiplication, dot product, and norm.

- **Matrices:**  
  - Represent arrays of numbers used to solve systems of equations, perform transformations, etc.
  - Operations include addition, subtraction, scalar multiplication, matrix multiplication, transpose, and, for square matrices, determinant and inverse.

Understanding these basic operations is essential for deeper studies in linear algebra and applications in data science, physics, computer graphics, and more.


# `adj(A)` — The Adjugate of a Matrix

## 📘 Definition

The **adjugate** (or **adjoint**) of a square matrix `A`, denoted as `adj(A)`, is defined as:


$adj(A) $ = transpose of the cofactor matrix of A
That is:
$$ adj(A) = Cof(A)^T$$


Where:
- `Cof(A)` is the **cofactor matrix** of `A`
- `^T` indicates the **transpose**

---

## 🧩 How to Compute `adj(A)`

### Step 1: Compute the Cofactor Matrix

For each element `a_ij` in matrix `A`:
1. **Remove** the `i`-th row and `j`-th column.
2. **Calculate the determinant** of the resulting smaller matrix (called the **minor**).
3. **Apply the sign** using the formula `(-1)^(i+j)` to get the **cofactor**.

Do this for each element in the matrix to construct the full **cofactor matrix**.

### Step 2: Transpose the Cofactor Matrix

Once you have the cofactor matrix, take its **transpose** to get the **adjugate** of `A`:



$$ A = \begin{bmatrix}1& 2& 3\\0 &4 &5\\ 1 &0 &6\end{bmatrix}$$

---

### Step 1: Cofactor Matrix

We'll compute some cofactors manually:

- **Cofactor of $a_{11}$**:
  
  $Minor = \begin{bmatrix}4&5\\0&6\end{bmatrix}
  $
  
  $Determinant = (4*6 - 0*5) = 24
  $
  
  $Cofactor = (+1) * 24 = 24$

- **Cofactor of $a_{12}$**:
  
  $Minor = \begin{bmatrix}0 &5 \\1 &6\end{bmatrix}$
  
  $Determinant = (0*6 - 1*5) = -5$
  
  $Cofactor = (-1) * -5 = 5$

- **Cofactor of $a_{13}$**:
  
  $Minor =\begin{bmatrix}0 &4 \\ 1 &0 \end{bmatrix}$
  
  $Determinant = (0*0 - 1*4) = -4$
  
  $Cofactor = (+1) * -4 = -4$

Repeat this process for all 9 elements to get the full cofactor matrix:


$$Cof(A) = \begin{bmatrix}24 &5 &-4\\-12 &3 &2\\ -2 &-5 &4\end{bmatrix}$$

---

### Step 2: Transpose the Cofactor Matrix

Now transpose it:

$$ adj(A) = \begin{bmatrix}24 &-12 &-2 \\ 5 &3 &-5 \\ -4 &2 &4  \end{bmatrix}$$


---

## ✅ Usage of `adj(A)`

The adjugate is used to compute the **inverse** of a matrix:

$$ A^{-1} = (1 / det(A)) * adj(A)$$

# 2. Eigenvalues and Eigenvectors <a name="eigen-values-vect"></a>

## 📘 What Are They?

Given a square matrix `A`, an **eigenvector** `v` and its corresponding **eigenvalue** `λ` satisfy the equation:

$$ A * v = λ * v $$

In words:
- Applying the matrix `A` to the vector `v` **only scales** it by `λ`.
- The **direction of `v` remains the same**, only its magnitude changes (unless `λ` is negative, then it flips).

---

## 🧠 Intuition

- **Eigenvectors** are directions that remain unchanged (up to scaling) when a transformation `A` is applied.
- **Eigenvalues** tell you **how much** the eigenvectors are stretched or compressed.

Example:  
If `λ = 2`, then `A` stretches `v` to twice its length.  
If `λ = 0.5`, it shrinks `v` to half.  
If `λ = -1`, it flips `v` to the opposite direction.

---

## 🧮 How to Compute

### Step 1: Solve the Characteristic Equation

We start from:

$$ A * v - λ * I * v = 0 ⇒ (A - λ * I) * v = 0$$


To find non-trivial solutions for `v`, the matrix `(A - λI)` must be **singular** (non-invertible), so:

$$(A - λ * I) * v = 0$$


This is called the **characteristic equation** — solve it to find all eigenvalues `λ`.

---

### Step 2: Find Eigenvectors for Each Eigenvalue

For each eigenvalue `λ`, solve the linear system:


This gives you the **eigenvectors** corresponding to `λ`.

---

## 🔢 Example

Let’s take a simple 2x2 matrix:

\begin{bmatrix}2 &1\\1 &2 \end{bmatrix}



### Step 1: Characteristic Equation

$$det(A - λI) = det(| 2-λ 1 | | 1 2-λ |)$$

$$= (2-λ)(2-λ) - (1)(1) = (2 - λ)^2 - 1 = λ^2 - 4λ + 3$$

Set it to 0:

$$ λ^2 - 4λ + 3 = 0 ⇒ λ = 1, 3$$


So the eigenvalues are `λ₁ = 1`, `λ₂ = 3`.

---

### Step 2: Find Eigenvectors

#### For λ = 1:

Solve `(A - I)v = 0`:
$$\begin{bmatrix} 1 &1 \\1 &1\end{bmatrix}
 * \begin{bmatrix} x\\y \end {bmatrix} = \begin{bmatrix} 0\\0 \end {bmatrix} $$

$$⇒ x + y = 0 ⇒ y = -x $$

Eigenvector:
$$v₁ = \begin{bmatrix} 1\\-1 \end {bmatrix} $$ (or any scalar multiple)

#### For λ = 3:

Solve `(A - 3*I)v = 0`:
$$\begin{bmatrix} -1 &1 \\1 &-1\end{bmatrix}
 * \begin{bmatrix} x\\y \end {bmatrix} = \begin{bmatrix} 0\\0 \end {bmatrix} $$

$$⇒ -x + y = 0
⇒ y = x$$

Eigenvector:
$$ v₂ = \begin{bmatrix} 1\\1 \end {bmatrix} $$ (or any scalar multiple)


---

## 📦 Summary

- **Eigenvalue** `λ`: Scalar that tells how much the eigenvector is stretched.
- **Eigenvector** `v`: Direction that remains unchanged (except scaling) when `A` is applied.
- Solve `det(A - λI) = 0` to find eigenvalues.
- Solve `(A - λI)v = 0` to find corresponding eigenvectors.

---

## 💡 Applications

- Principal Component Analysis (PCA)
- Vibration modes in physics
- Google's PageRank algorithm
- Quantum mechanics
- Image compression

---
### Code implementation:

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[4, 2],
              [1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("Matrix A:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors (each column is an eigenvector):")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors (each column is an eigenvector):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# ✅ 3. Matrix Decompositions <a name="mat-decomp"></a>

## 📘 What Is a Matrix Decomposition?

Matrix decomposition (also called matrix factorization) is the process of **breaking a matrix into a product of simpler matrices**.  
This is extremely useful in linear algebra, especially for:
- Solving systems of equations
- Computing matrix inverses
- Performing numerical analysis efficiently

---

## 🔓 Common Matrix Decompositions

Here are the most important types of matrix decompositions:

---

## 🔹 1. LU Decomposition (Lower-Upper)

**LU decomposition** writes a square matrix `A` as the product of a **lower triangular matrix `L`** and an **upper triangular matrix `U`**:

$$ A = L*U$$


Where:
- `L` has ones on the diagonal and non-zero values below the diagonal
- `U` has zeros below the diagonal

🔧 Useful for:
- Solving `Ax = b` by forward and backward substitution
- Efficient matrix inversion

✅ Only works for **square matrices**, and sometimes needs **row swapping** (i.e., partial pivoting), which gives `PA = LU`, where `P` is a permutation matrix.

---

## 🔹 2. QR Decomposition

**QR decomposition** factors a matrix `A` into:

$$A = Q * R$$


Where:
- `Q` is an orthogonal matrix (`QᵀQ = I`)
- `R` is an upper triangular matrix

🔧 Useful for:
- Solving least squares problems
- Orthogonalization

✅ Works on **any m × n matrix** (not necessarily square).

---

## 🔹 3. Cholesky Decomposition

**Cholesky decomposition** is for **symmetric, positive-definite matrices**.

$$ A = L * L^T$$


Where:
- `L` is a lower triangular matrix
- `Lᵀ` is the transpose of `L`

🔧 Faster and more stable than LU for certain systems  
✅ Works only when `A` is **symmetric** and **positive definite**.

---

## 🔹 4. Eigenvalue Decomposition

This decomposition uses eigenvalues and eigenvectors:

$$A = V * D * V^{⁻1}$$


Where:
- `D` is a diagonal matrix containing the eigenvalues
- `V` contains the eigenvectors as columns

✅ Works when `A` has **enough linearly independent eigenvectors** (i.e., is diagonalizable)

🔧 Useful in:
- PCA
- System dynamics
- Matrix powers

---

## 🔹 5. Singular Value Decomposition (SVD)

**SVD** is one of the most powerful decompositions and works for **any m × n matrix**:

$$ A = U * Σ * V^T $$


Where:
- `U` is an orthogonal matrix of left singular vectors
- `Σ` is a diagonal matrix of singular values
- `Vᵀ` is the transpose of an orthogonal matrix of right singular vectors

✅ Works for **any matrix** (square or rectangular)

🔧 Extremely useful for:
- Dimensionality reduction
- Image compression
- PCA
- Noise filtering



---



## 🧠 Why Matrix Decompositions Matter

Matrix decompositions help us:
- Solve linear systems more efficiently
- Understand the structure of matrices
- Perform machine learning (PCA, regression)
- Speed up computations (e.g., with SVD or Cholesky)

---

## 🧰 Summary Table

| Name       | Form             | Conditions                        | Use Cases                       |
|------------|------------------|-----------------------------------|----------------------------------|
| LU         | A = L * U        | Square matrix                     | Solve linear systems            |
| QR         | A = Q * R        | Any m × n matrix                  | Least squares, orthogonal basis |
| Cholesky   | A = L * Lᵀ       | Symmetric, positive-definite      | Fast solve for special matrices |
| Eigen      | A = V * D * V⁻¹  | Diagonalizable (enough eigvecs)   | PCA, dynamics, matrix functions |
| SVD        | A = U * Σ * Vᵀ   | Any matrix                        | PCA, compression, LSI           |

---



## Example: LU Decomposition

Let:



$A = \begin{bmatrix} 4 &3\\6 &3 \end {bmatrix}$

Decompose into `L` and `U`:

$L = \begin{bmatrix} 1 &0\\1.5 &1 \end {bmatrix}$

$U = \begin{bmatrix} 4 &3\\0 &-1.5 \end {bmatrix}$

Check:  
`L * U = A`

To find this solution fist supose:

$L = \begin{bmatrix} 1 &0\\l_{21} &1 \end {bmatrix}$


$U = \begin{bmatrix} u_{11} &u_{12}\\0 &u_{22} \end {bmatrix}$

This product must equal to $A$:

$L*U = \begin{bmatrix} 1 &0\\l_{21} &1 \end {bmatrix} *
\begin{bmatrix} u_{11} &u_{12}\\0 &u_{22} \end {bmatrix} = \begin{bmatrix} u_{11} &u_{12}\\l_{21}*u_{11} &l_{21}*u_{12}+u_{22} \end {bmatrix}  $

Then:

$ u_{11} = 4$

$ u_{12} = 3$

$l_{21}*u_{11} = 6 ⇒ l_{21} = 1.5 $

$ l_{21}*u_{12} + u_{22} = 3 ⇒ 1.5*3 + u_{22} = 3⇒ u_{22}= -1.5$

### Code verification:

In [ ]:
import numpy as np
from scipy.linalg import lu
# Define matrix A as a NumPy array
A = np.array([[4, 3],
              [6, 3]])

L = np.array([[1, 0],
              [1.5, 1]])
U = np.array([[4, 3],
              [0, -1.5]])
# Verify that P @ A == L @ U
LU = L @ U

print("A:\n", A)
print("L:\n", L)
print("U:\n", U)
print("L @ U:\n", LU)
print("Match:", np.allclose(A, LU))


A:
 [[4 3]
 [6 3]]
L:
 [[1.  0. ]
 [1.5 1. ]]
U:
 [[ 4.   3. ]
 [ 0.  -1.5]]
L @ U:
 [[4. 3.]
 [6. 3.]]
Match: True


### Code implementation of LU decomposition:

In [ ]:

# Define the matrix A
A = np.array([[4, 3],
              [6, 3]])

# LU decomposition with partial pivoting
P, L, U = lu(A)

# Compute both sides
PA = P @ A
LU = L @ U

# Display results
print("A:\n", A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
print("P @ A:\n", PA)
print("L @ U:\n", LU)
print("Match:", np.allclose(PA, LU))  # Should be True

A:
 [[4 3]
 [6 3]]
P:
 [[0. 1.]
 [1. 0.]]
L:
 [[1.         0.        ]
 [0.66666667 1.        ]]
U:
 [[6. 3.]
 [0. 1.]]
P @ A:
 [[6. 3.]
 [4. 3.]]
L @ U:
 [[6. 3.]
 [4. 3.]]
Match: True


---
## Example: QR Decomposition

Let:



$A = \begin{bmatrix} 12 &-51\\6 &167\\-4 &24 \end {bmatrix}$


### QR Decomposition of A using Gram–Schmidt

We want to decompose

$$
A = \begin{bmatrix}
12 & -51 \\
6 & 167 \\
-4 & 24
\end{bmatrix}
$$

into

$$
A = Q R,
$$

where:
- **Q** is an orthonormal matrix (its columns are unit vectors and are mutually orthogonal),
- **R** is an upper triangular matrix.

### Step 1: Write Down the Columns of A

Let $
\mathbf{a}_1 = \begin{bmatrix} 12 \\ 6 \\ -4 \end{bmatrix}, \quad
\mathbf{a}_2 = \begin{bmatrix} -51 \\ 167 \\ 24 \end{bmatrix}.
$
### Step 2: Find
$\mathbf{q}_1$ by Normalizing $\mathbf{a}_1$

Compute the norm of $\mathbf{a}_1$:

$$
\|\mathbf{a}_1\| = \sqrt{12^2 + 6^2 + (-4)^2} = \sqrt{144 + 36 + 16} = \sqrt{196} = 14.
$$

Then, the first orthonormal vector is

$$
\mathbf{q}_1 = \frac{1}{14}\mathbf{a}_1 = \frac{1}{14} \begin{bmatrix} 12 \\ 6 \\ -4 \end{bmatrix} = \begin{bmatrix} \frac{6}{7} \\ \frac{3}{7} \\ -\frac{2}{7} \end{bmatrix}.
$$

### Step 3: Orthogonalize
$\mathbf{a}_2$ Against $\mathbf{q}_1$

First, compute the projection of $\mathbf{a}_2$ onto $\mathbf{q}_1$:

$$
r_{12} = \mathbf{q}_1^\top \mathbf{a}_2 = (\frac{6}{7})(-51) + (\frac{3}{7} )(167) + (-\frac{2}{7} )(24)=\frac{147}{7}= 21 .
$$





Now, the projection is:

$$
\text{proj}_{\mathbf{q}_1}(\mathbf{a}_2) = r_{12}\,\mathbf{q}_1 = 21 \cdot \begin{bmatrix} \frac{6}{7} \\ \frac{3}{7} \\ -\frac{2}{7} \end{bmatrix} = \begin{bmatrix} 18 \\ 9 \\ -6 \end{bmatrix}
$$

Subtract this projection from $\mathbf{a}_2$ to get the orthogonal component $\mathbf{u}_2$:

$$
\mathbf{u}_2 = \mathbf{a}_2 - \text{proj}_{\mathbf{q}_1}(\mathbf{a}_2) = \begin{bmatrix} -51 \\ 167 \\ 24 \end{bmatrix} - \begin{bmatrix} 18 \\ 9 \\ -6 \end{bmatrix} = \begin{bmatrix} -69 \\ 158 \\ 30 \end{bmatrix}.
$$

### Step 4: Normalize
$\mathbf{u}_2$ to Get $\mathbf{q}_2$

Compute the norm of $\mathbf{u}_2$:

$$
\|\mathbf{u}_2\| = \sqrt{(-69)^2 + 158^2 + 30^2} = \sqrt{4761 + 24964 + 900} = \sqrt{30625} = 175.
$$

Then,

$$
\mathbf{q}_2 = \frac{1}{175}\mathbf{u}_2 = \frac{1}{175} \begin{bmatrix} -69 \\ 158 \\ 30 \end{bmatrix} = \begin{bmatrix} -0.3943 \\ 0.9029 \\ 0.1714 \end{bmatrix}.
$$

### Step 5: Assemble Q and R

Now we can form the matrix $ Q $ whose columns are $\mathbf{q}_1$ and $\mathbf{q}_2$:

$$
Q = \begin{bmatrix}
0.8571 & -0.3943 \\
0.4286 & 0.9029 \\
-0.2857 & 0.1714
\end{bmatrix}.
$$

For $ R $, the entries come from:
- $ r_{11} = \|\mathbf{a}_1\| = 14, $
- $ r_{12} = 21, $
- $ r_{22} = \|\mathbf{u}_2\| = 175. $

Thus,

$$
R = \begin{bmatrix}
14 & 21 \\
0 & 175
\end{bmatrix}.
$$

### Step 6: Verify
 $$ Q R = A $$

Multiply $ Q $ and $ R $:

$$
Q R = \begin{bmatrix}
0.8571 & -0.3943 \\
0.4286 & 0.9029 \\
-0.2857 & 0.1714
\end{bmatrix}
\begin{bmatrix}
14 & 21 \\
0 & 175
\end{bmatrix}.
$$

Performing the multiplication:

- **First Column:**

  $$
  \begin{bmatrix}
  0.8571 \times 14 + (-0.3943) \times 0 \\
  0.4286 \times 14 + 0.9029 \times 0 \\
  -0.2857 \times 14 + 0.1714 \times 0
  \end{bmatrix} = \begin{bmatrix}
  12 \\
  6 \\
  -4
  \end{bmatrix}.
  $$

- **Second Column:**

  $$
  \begin{bmatrix}
  0.8571 \times 21 + (-0.3943) \times 175 \\
  0.4286 \times 21 + 0.9029 \times 175 \\
  -0.2857 \times 21 + 0.1714 \times 175
  \end{bmatrix} \approx \begin{bmatrix}
  -51 \\
  167 \\
  24
  \end{bmatrix}.
  $$

Thus, we recover

$$
Q R = \begin{bmatrix}
12 & -51 \\
6 & 167 \\
-4 & 24
\end{bmatrix} = A.
$$

✅ The QR decomposition is verified.


### Final Result

$$
\boxed{
Q = \begin{bmatrix}
0.8571 & -0.3943 \\
0.4286 & 0.9029 \\
-0.2857 & 0.1714
\end{bmatrix}, \quad
R = \begin{bmatrix}
14 & 21 \\
0 & 175
\end{bmatrix}
}
$$



### Code Verification:


In [ ]:

import numpy as np

Q = np.array([
    [0.8571, -0.3943],
    [0.4286, 0.9029],
    [-0.2857, 0.1714]
])
R = np.array([
    [14, 21],
    [0, 175]
])

A = Q @ R
print("A =\n", np.round(A, decimals=0))
# Expected output:
# [[ 12. -51.]
#  [  6. 167.]
#  [ -4.  24.]]

A =
 [[ 12. -51.]
 [  6. 167.]
 [ -4.  24.]]


### Code implementation:

In [ ]:
import numpy as np

# Define matrix A
A = np.array([[12, -51],
              [6, 167],
              [-4, 24]])

# Perform QR decomposition using numpy's qr function
Q, R = np.linalg.qr(A)

# Print Q and R, rounded for readability
print("Q:")
print(np.round(Q, 4))
print("\nR:")
print(np.round(R, 4))

# Verify that Q @ R equals A
A_reconstructed = Q @ R
print("\nA reconstructed (Q @ R):")
print(np.round(A_reconstructed, 4))
print("\nMatch:", np.allclose(A, A_reconstructed))


Q:
[[-0.8571  0.3943]
 [-0.4286 -0.9029]
 [ 0.2857 -0.1714]]

R:
[[ -14.  -21.]
 [   0. -175.]]

A reconstructed (Q @ R):
[[ 12. -51.]
 [  6. 167.]
 [ -4.  24.]]

Match: True


### Use Cases:
- Solving least squares problems

- Constructing orthonormal bases

- Numerical stability in solving systems of equations
---

## Example: Cholesky decomposition

$$ A = L * L^T $$

Where:
- `L` is a **lower triangular matrix**
- `Lᵀ` is the transpose of `L`

✅ More efficient than LU decomposition when the matrix meets the criteria.


Let the symmetric positive definite matrix:

$$
A = \begin{bmatrix}
25 & 15 & -5 \\
15 & 18 & 0 \\
-5 & 0 & 11
\end{bmatrix}
$$

we want to find a lower triangular matrix \(L\) such that

$$
A = L L^T
$$

The matrix \(L\) is assumed to have the form

$$
L = \begin{bmatrix}
l_{11} & 0      & 0 \\
l_{21} & l_{22} & 0 \\
l_{31} & l_{32} & l_{33}
\end{bmatrix}
$$

### Step 1: Find $l_{11}$

The \((1,1)\) entry of \(A\) is given by

$$
A_{11} = l_{11}^2.
$$

Since $A_{11} = 25\$, we have

$$
l_{11} = \sqrt{25} = 5.
$$

### Step 2: Find $l_{21}$ and $l_{31}$

For the first column of \(L\):

- The \((2,1)\) entry:
  
  $$
  A_{21} = l_{21} \cdot l_{11}.
  $$

  Given $A_{21} = 15$ and $l_{11} = 5$, we find

  $$
  l_{21} = \frac{15}{5} = 3.
  $$

- The \((3,1)\) entry:

  $$
  A_{31} = l_{31} \cdot l_{11}.
  $$

  Given $A_{31} = -5$ and $l_{11} = 5$, we have

  $$
  l_{31} = \frac{-5}{5} = -1.
  $$

### Step 3: Find $l_{22}$

Next, consider the \((2,2)\) entry:

The formula is

$$
A_{22} = l_{21}^2 + l_{22}^2.
$$

Given $A_{22} = 18$ and $l_{21} = 3$:

$$
18 = 3^2 + l_{22}^2 \quad \Longrightarrow \quad 18 = 9 + l_{22}^2.
$$

Thus,

$$
l_{22}^2 = 18 - 9 = 9 \quad \Longrightarrow \quad l_{22} = \sqrt{9} = 3.
$$

### Step 4: Find $l_{32}$

For the $(3,2)$ entry, we have

$$
A_{32} = l_{31} \cdot l_{21} + l_{32} \cdot l_{22}.
$$

Given $A_{32} = 0,l_{31} = -1,l_{21} = 3,l_{22} = 3$:

$$
0 = (-1)(3) + 3l_{32} \quad \Longrightarrow \quad 0 = -3 + 3l_{32}.
$$

Thus,

$$
3l_{32} = 3 \quad \Longrightarrow \quad l_{32} = 1.
$$

### Step 5: Find $l_{33}$

Finally, for the $(3,3)$ entry:

$$
A_{33} = l_{31}^2 + l_{32}^2 + l_{33}^2.
$$

Given $A_{33} = 11, l_{31} = -1, l_{32} = 1$:

$$
11 = (-1)^2 + 1^2 + l_{33}^2 \quad \Longrightarrow \quad 11 = 1 + 1 + l_{33}^2.
$$

So,

$$
l_{33}^2 = 11 - 2 = 9 \quad \Longrightarrow \quad l_{33} = \sqrt{9} = 3.
$$

### Final \(L\) Matrix

Putting it all together, we have

$$
L = \begin{bmatrix}
5 & 0 & 0 \\
3 & 3 & 0 \\
-1 & 1 & 3
\end{bmatrix}.
$$

### Verification

We can verify the decomposition by computing $L L^T$:

$$
L L^T = \begin{bmatrix}
5 & 0 & 0 \\
3 & 3 & 0 \\
-1 & 1 & 3
\end{bmatrix}
\begin{bmatrix}
5 & 3 & -1 \\
0 & 3 & 1 \\
0 & 0 & 3
\end{bmatrix}.
$$

- **(1,1) entry:** \(5 \times 5 = 25\).
- **(1,2) entry:** \(5 \times 3 = 15\).
- **(1,3) entry:** \(5 \times -1 = -5\).

- **(2,1) entry:** \(3 \times 5 = 15\).
- **(2,2) entry:** \(3 \times 3 + 3 \times 3 = 9 + 9 = 18\).
- **(2,3) entry:** \(3 \times -1 + 3 \times 1 = -3 + 3 = 0\).

- **(3,1) entry:** \((-1) \times 5 = -5\).
- **(3,2) entry:** \((-1) \times 3 + 1 \times 3 = -3 + 3 = 0\).
- **(3,3) entry:** \((-1)^2 + 1^2 + 3^2 = 1 + 1 + 9 = 11\).

Thus,

$$
L L^T = \begin{bmatrix}
25 & 15 & -5 \\
15 & 18 & 0 \\
-5 & 0 & 11
\end{bmatrix} = A.
$$

✅ The Cholesky decomposition is verified!

### Final Answer

$$
\boxed{
L = \begin{bmatrix}
5 & 0 & 0 \\
3 & 3 & 0 \\
-1 & 1 & 3
\end{bmatrix}, \quad \text{and} \quad A = L L^T.
}
$$

### Code verification and implementation:


In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[25, 15, -5],
              [15, 18,  0],
              [-5,  0, 11]])

# Compute the Cholesky decomposition using NumPy's linalg.cholesky.
# Note: np.linalg.cholesky returns a lower-triangular L such that A = L @ L.T.
L = np.linalg.cholesky(A)

# Print the original matrix A
print("A =\n", A)

# Print the computed lower triangular matrix L
print("\nL (from np.linalg.cholesky) =\n", L)

# Compute L @ L.T to verify the decomposition
A_reconstructed = L @ L.T
print("\nL @ L.T =\n", np.round(A_reconstructed, decimals=4))

# Check if the reconstruction is close to A
print("\nMatch:", np.allclose(A, A_reconstructed))


A =
 [[25 15 -5]
 [15 18  0]
 [-5  0 11]]

L (from np.linalg.cholesky) =
 [[ 5.  0.  0.]
 [ 3.  3.  0.]
 [-1.  1.  3.]]

L @ L.T =
 [[25. 15. -5.]
 [15. 18.  0.]
 [-5.  0. 11.]]

Match: True


## SVD Decomposition of A

Given

$$
A = \begin{bmatrix} 3 & 1 \\ 0 & 2 \end{bmatrix},
$$

we want to find matrices \(U\), \(\Sigma\), and \(V\) such that

$$
A = U\, \Sigma\, V^T.
$$

### Step 1: Compute \(A^T A\)

First, form the matrix

$$
A^T A = \begin{bmatrix} 3 & 0 \\ 1 & 2 \end{bmatrix}
\begin{bmatrix} 3 & 1 \\ 0 & 2 \end{bmatrix}
= \begin{bmatrix}
3 \cdot 3 + 0 \cdot 0 & 3 \cdot 1 + 0 \cdot 2 \\
1 \cdot 3 + 2 \cdot 0 & 1 \cdot 1 + 2 \cdot 2
\end{bmatrix}
= \begin{bmatrix}
9 & 3 \\
3 & 5
\end{bmatrix}.
$$

### Step 2: Find the Eigenvalues of \(A^T A\)

Solve the characteristic equation

$$
\det(A^T A - \lambda I) = 0.
$$

That is,

$$
\det\begin{bmatrix} 9-\lambda & 3 \\ 3 & 5-\lambda \end{bmatrix} = (9-\lambda)(5-\lambda) - 3 \cdot 3 = 0.
$$

Compute:

$$
(9-\lambda)(5-\lambda) - 9 = \lambda^2 - 14\lambda + 45 - 9 = \lambda^2 - 14\lambda + 36 = 0.
$$

Solve the quadratic equation

$$
\lambda^2 - 14\lambda + 36 = 0.
$$

The discriminant is

$$
\Delta = 14^2 - 4 \cdot 36 = 196 - 144 = 52.
$$

Thus, the eigenvalues are

$$
\lambda_{1,2} = \frac{14 \pm \sqrt{52}}{2} = \frac{14 \pm 2\sqrt{13}}{2} = 7 \pm \sqrt{13}.
$$

The singular values are the square roots of these eigenvalues:

$$
\sigma_1 = \sqrt{7 + \sqrt{13}}, \quad \sigma_2 = \sqrt{7 - \sqrt{13}}.
$$

For numerical approximations (with \(\sqrt{13} \approx 3.606\)):

- \(7 + \sqrt{13} \approx 10.606\) so \(\sigma_1 \approx \sqrt{10.606} \approx 3.256\),
- \(7 - \sqrt{13} \approx 3.394\) so \(\sigma_2 \approx \sqrt{3.394} \approx 1.843\).

### Step 3: Find the Right Singular Vectors (Columns of \(V\))

The eigenvectors of \(A^T A\) form the columns of \(V\).

**For \(\lambda_1 = 7 + \sqrt{13}\):**

Solve

$$
\left(\begin{bmatrix} 9 & 3 \\ 3 & 5 \end{bmatrix} - (7+\sqrt{13})I\right) \mathbf{v} = 0.
$$

That is,

$$
\begin{bmatrix}
9 - (7+\sqrt{13}) & 3 \\
3 & 5 - (7+\sqrt{13})
\end{bmatrix}
=
\begin{bmatrix}
2 - \sqrt{13} & 3 \\
3 & -2 - \sqrt{13}
\end{bmatrix}.
$$

A nonzero eigenvector \(\mathbf{v}_1 = \begin{bmatrix} x \\ y \end{bmatrix}\) satisfies:

$$
(2 - \sqrt{13}) x + 3y = 0 \quad \Longrightarrow \quad y = \frac{\sqrt{13}-2}{3}\, x.
$$

Choose \(x = 1\) (for instance), then

$$
\mathbf{v}_1 = \begin{bmatrix} 1 \\ \frac{\sqrt{13}-2}{3} \end{bmatrix}.
$$

Normalize \(\mathbf{v}_1\) to obtain the first column of \(V\).

**For \(\lambda_2 = 7 - \sqrt{13}\):**

Similarly, solve

$$
\begin{bmatrix}
9 - (7-\sqrt{13}) & 3 \\
3 & 5 - (7-\sqrt{13})
\end{bmatrix}
=
\begin{bmatrix}
2 + \sqrt{13} & 3 \\
3 & -2 + \sqrt{13}
\end{bmatrix}.
$$

A nonzero eigenvector \(\mathbf{v}_2 = \begin{bmatrix} x \\ y \end{bmatrix}\) satisfies:

$$
(2 + \sqrt{13}) x + 3y = 0 \quad \Longrightarrow \quad y = -\frac{2+\sqrt{13}}{3}\, x.
$$

Choose \(x = 1\) and normalize \(\mathbf{v}_2\) to obtain the second column of \(V\).

For simplicity, after normalization we might denote (approximately):

$$
V = \begin{bmatrix}
0.881 & -0.472 \\
0.472 & 0.881
\end{bmatrix},
$$

where each column is normalized and the second vector is chosen to be orthogonal to the first.

### Step 4: Compute the Left Singular Vectors (Columns of \(U\))

Use the formula

$$
\mathbf{u}_i = \frac{1}{\sigma_i} A\, \mathbf{v}_i.
$$

For \(i=1,2\):

- Compute $\mathbf{u}_1 = \frac{1}{\sigma_1} A\mathbf{v}_1$

- Compute $\mathbf{u}_2 = \frac{1}{\sigma_2} A\, \mathbf{v}_2$

These $\mathbf{u}_i$ will form the columns of $U$.

### Step 5: Assemble the SVD

Finally, the SVD is

$$
A = U\, \Sigma\, V^T,
$$

with

- $\Sigma = \begin{bmatrix} \sigma_1 & 0 \\ 0 & \sigma_2 \end{bmatrix} $
- $ U $ containing the left singular vectors
- $ V $ containing the right singular vectors

---

### Final Answer (Approximate Numerical Values)

Using the approximations above, we have:

- **Singular Values:**  
   $\sigma_1 \approx 3.256 $,  
  $ \sigma_2 \approx 1.843 $

- **Right Singular Vectors (Columns of \(V\)) (approx.):**

  $$
  V \approx \begin{bmatrix}
  0.881 & -0.472 \\
  0.472 & 0.881
  \end{bmatrix}.
  $$

- **Left Singular Vectors:**  
  Compute \(U\) as  
  $$
  \mathbf{u}_1 \approx \frac{1}{3.256} A\, \mathbf{v}_1, \quad \mathbf{u}_2 \approx \frac{1}{1.843} A\, \mathbf{v}_2.
  $$

Thus, the SVD of \(A\) is

$$
A \approx U\, \begin{bmatrix} 3.256 & 0 \\ 0 & 1.843 \end{bmatrix}\, V^T.
$$

*Note:* The exact numbers depend on the normalization of the eigenvectors; the key steps are:  
1. Compute $A^T A$  
2. Find its eigenvalues (the squares of the singular values) and eigenvectors (to form $V$,  
3. Compute the singular values as the square roots of the eigenvalues, and  
4. Compute $U = A\,V\,\Sigma^{-1}$.

---

This step-by-step process outlines how SVD is derived manually for the given matrix.


In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[3, 1],
              [0, 2]])

# Compute the SVD of A using numpy.linalg.svd.
# full_matrices=False ensures that U and Vt are of shapes (m, n) and (n, n) respectively.
U, S, Vt = np.linalg.svd(A, full_matrices=False)

# Create the Sigma matrix (diagonal matrix of singular values)
Sigma = np.diag(S)

# Display the results
print("Matrix A:")
print(A)

print("\nMatrix U (left singular vectors):")
print(U)

print("\nSingular values (as a 1D array):")
print(S)

print("\nMatrix Sigma (diagonal matrix of singular values):")
print(Sigma)

print("\nMatrix Vt (transpose of right singular vectors):")
print(Vt)

# Verify the decomposition by reconstructing A
A_reconstructed = U @ Sigma @ Vt
print("\nReconstructed A (U @ Sigma @ Vt):")
print(np.round(A_reconstructed, decimals=4))

# Check if A and A_reconstructed are close
print("\nMatch:", np.allclose(A, A_reconstructed))

Matrix A:
[[3 1]
 [0 2]]

Matrix U (left singular vectors):
[[ 0.95709203 -0.28978415]
 [ 0.28978415  0.95709203]]

Singular values (as a 1D array):
[3.25661654 1.84240298]

Matrix Sigma (diagonal matrix of singular values):
[[3.25661654 0.        ]
 [0.         1.84240298]]

Matrix Vt (transpose of right singular vectors):
[[ 0.8816746   0.47185793]
 [-0.47185793  0.8816746 ]]

Reconstructed A (U @ Sigma @ Vt):
[[3. 1.]
 [0. 2.]]

Match: True
